"""initial migration

Revision ID: 47f07bc70440
Revises: 
Create Date: 2025-01-18 12:57:52.851448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f07bc70440'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamento',
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('sala', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flg_ativo', sa.Boolean(), nullable=True),
    sa.Column('flg_excluido', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamento_codigo'), 'agendamento', ['codigo'], unique=False)
    op.create_index(op.f('ix_agendamento_email'), 'agendamento', ['email'], unique=False)
    op.create_index(op.f('ix_agendamento_flg_ativo'), 'agendamento', ['flg_ativo'], unique=False)
    op.create_index(op.f('ix_agendamento_flg_excluido'), 'agendamento', ['flg_excluido'], unique=False)
    op.create_index(op.f('ix_agendamento_id'), 'agendamento', ['id'], unique=False)
    op.create_index(op.f('ix_agendamento_responsavel'), 'agendamento', ['responsavel'], unique=False)
    op.create_index(op.f('ix_agendamento_sala'), 'agendamento', ['sala'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agendamento_sala'), table_name='agendamento')
    op.drop_index(op.f('ix_agendamento_responsavel'), table_name='agendamento')
    op.drop_index(op.f('ix_agendamento_id'), table_name='agendamento')
    op.drop_index(op.f('ix_agendamento_flg_excluido'), table_name='agendamento')
    op.drop_index(op.f('ix_agendamento_flg_ativo'), table_name='agendamento')
    op.drop_index(op.f('ix_agendamento_email'), table_name='agendamento')
    op.drop_index(op.f('ix_agendamento_codigo'), table_name='agendamento')
    op.drop_table('agendamento')
    # ### end Alembic commands ###
